spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: 1234
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
    #    show-sql: true
    properties:
      #      hibernate:
      #        show-sql: true
      #        format-sql: true
      javax:
        persistence:
          validation:
            mode: none

logging:
  level:
    root: info
    com.developia.hibernateexample: debug